name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  APP_NAME: go-fibonacci-api
  OVERLAY: dev

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/go-fibonacci-api

    outputs:
      SHORT_SHA: ${{ steps.vars.outputs.SHORT_SHA }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Verify Go installation
        run: go version

      - name: Initialize Go module (if needed)
        run: |
          if [ ! -f go.mod ]; then
            go mod init go-math-api
          fi

      - name: Build the Go application
        run: CGO_ENABLED=0 go build -o main .

      - name: Run unit tests
        run: CGO_ENABLED=0 go test -v ./...

      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run:  docker build -t $IMAGE_NAME:${{ steps.vars.outputs.SHORT_SHA }} .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:${{ steps.vars.outputs.SHORT_SHA }}